config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end
  resources :attachments, only: [:destroy]

  resources :search, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
  
  mount ActionCable.server => '/cable'
  
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachmentable, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  validates :title, :body, presence: true
  validates :title, length: { minimum: 5, maximum: 255 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  after_create :subscribe_author

  private

  def subscribe_author
    subscriptions.create(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  before_action :get_question, only: [:show]

  respond_to :json

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question, serializer: SingleQuestionSerializer
  end

  def create
    respond_with @current_resource_owner.questions.create(question_params)
  end

  private

  def get_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  include Voted

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :build_answer, only: :show
  after_action :publish_question, only: [:create]

  respond_to :js, :json
  
  authorize_resource

  def index
    respond_with (@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with (@question = current_user.questions.new)
  end

  def edit
  end

  def create
    respond_with (@question = current_user.questions.create(question_params))
  end

  def update
    @question.update(question_params) if current_user.check_author(@question)
    respond_with @question
  end

  def destroy
    @question.destroy if current_user.check_author(@question)
    respond_with @question
  end

  private

  def load_question
    @question = Question.find(params[:id])
    gon.question_id = @question.id
  end

  def build_answer
    @answer = @question.answers.new
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question_part',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.slim
h1 Answers:
.answers-all
  = render @question.answers

app/views/questions/_attachments_fields.html.slim
- if question.attachments.present?
  #attachments
    ul 
      = render question.attachments

app/views/questions/_form.html.slim
= render 'common/errors', resource: @question
.row
.col-lg-6.col-md-8.col-sm-12
  = form_for @question do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :body
      = f.text_area :body, class: 'form-control'
    div
      = f.submit 'Create', class: 'btn btn-primary'
      p Attachments:
    .form-group
      = f.fields_for :attachments, @question.attachments.build do |a|
        = render 'attachments/attachment_fields', f: a
        = link_to_add_association '+ Add file', f, :attachments, partial: 'attachments/attachment_fields'
          
      = link_to 'Back', questions_path, type: 'button', class: 'btn btn-default cancel'

app/views/questions/_form_edit.html.slim
= render 'common/errors', resource: @question
.row
  .col-lg-6.col-md-8.col-sm-12
    = form_for @question, remote: true do |f|
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'
      div
        = button_tag 'Cancel', type: 'button', class: 'btn btn-default cancel'
        = f.submit 'Update question', class: 'btn btn-primary'

app/views/questions/_question.html.slim
.question-all
  h1 = question.title
  p = question.body
  = render 'votes/vote', resource: @question
  -if question.attachments.any?
    p Attachments:
    ul
      - @question.attachments.each do |a|
        div id="attach_#{a.id}"
          li= link_to a.file.identifier, a.file.url
          - if user_signed_in? && current_user.check_author(a.attachmentable)
              li= link_to 'delete', attachment_path(a), method: :delete, remote: true, data: {confirm: "Are you sure?"}
  -else 
   p No attachments yet
  -if can?(:edit, question)
    = link_to 'Edit', '', class: 'edit-question-link btn btn-default', data: { question_id: question.id }
  -if can?(:destroy, question)
    = link_to 'Delete', [question], class: 'delete-question-link btn btn-default ', method: :delete, remote: true, data: {confirm: "Are you sure?"}
  -if can?(:edit, question)
    p = form_for question, remote: true, html: { id: "edit-question-#{question.id}" } do |f|
        .form-group
          = f.label :title
          = f.text_field :title, class: 'form-control'
        .form-group
          = f.label :body
          = f.text_area :body, class: 'form-control'
        p= f.submit 'Save', class: 'btn btn-default'
  = link_to 'Back', questions_path

app/views/questions/_question_part.html.slim
th Title
th Questions
tr
  td.question_title = link_to question.title, question_path(question)
  td = question.body

app/views/questions/edit.html.slim
h1 Edit Question
= render 'form_edit'

app/views/questions/index.html.slim
h1 Welcome on SOFA - StackOverFlow analog)
table.table
  tr#questions
  - @questions.each do |question|
    th Title
    th Questions
    tr
      td.question_title = link_to question.title, question_path(question)
      td = question.body
br
-if can? :create, Question
  p= link_to 'Ask Question', new_question_path

app/views/questions/new.html.slim
h1 New Question
= render 'form'

app/views/questions/show.html.slim
- cache @question do
  = render @question
  .errors
  p
  .question id="question_#{@question.id}"
    .question_attachment
      .question-comments
      -if can? :create, Comment
        div id="add-comment-to-question-#{@question.id}"
          = render partial: 'comments/form', locals: { commentable: @question }
    -if @question.comments.any?
      h2 Comments
      = render @question.comments
    -else
      p No comments yet
  h2 Subscriptions
  div id="question-#{@question.id}-subscriptions" class = 'question-subscriptions'
    = render 'subscriptions/subscription', question: @question
  .answers
    - if @question.answers.count > 0
        = render 'answers'
    - else
        p class="empty-text" No answers yet.
    .form-group
    = form_for [@question, @answer], remote: true do |f|
      .form-group
        = f.label :body
        .answer-errors
        = f.text_area :body, class: 'form-control'
        p Attachments:
        .form-group 
          = f.fields_for :attachments, @answer.attachments.build do |a|
            = render 'attachments/attachment_fields', f: a
            = link_to_add_association '+ Add file', f, :attachments, partial: 'attachments/attachment_fields'
        = f.submit 'Add Answer', class: 'btn btn-primary'

app/views/questions/update.js.erb
<% if @question.errors.present? %>
    <% @question.errors.full_messages.each do |message| %>
        $('.question-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('.question-all').html('<%= j render @question %>');
    $('.edit-question-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        question_id = $(this).data('questionId');
        $('form#edit-question-' + question_id).show();
    });
<% end %>