config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end
  resources :attachments, only: [:destroy]

  resources :search, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
  
  mount ActionCable.server => '/cable'
  
end

app/models/search.rb
class Search

  OBJECTS = %w(everywhere answers questions comments users)

  def self.find(query, object)
    return [] unless OBJECTS.include? object
    query = ThinkingSphinx::Query.escape(query)
    return ThinkingSphinx.search(query) if object == 'everywhere'
    object.classify.constantize.search(query)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @results = Search.find(params[:query], params[:object])
    respond_with(@results)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_answer.html.slim
li.list-group-item
  = link_to response.body, question_path(response.question) + "#answer_#{response.id}"

app/views/search/_comment.html.slim
li.list-group-item
  - if response.commentable_type == 'Question'
    = link_to response.body, question_path(response.commentable_id) + "#comment_#{response.id}"
  - else
    = link_to response.body, question_path(response.commentable.question_id) + "#comment_#{response.id}"

app/views/search/_form.html.slim
= form_tag search_index_path, method: :get, class: 'navbar-form navbar-left' do
  = text_field_tag :query, @query, placeholder: 'Query', class: 'form-control'
  = select_tag :object, options_for_select(Search::OBJECTS, @object), class: 'form-control'
  = submit_tag 'Search ', class: 'btn btn-default'

app/views/search/_question.html.slim
li.list-group-item
  = link_to response.title, question_path(response)

app/views/search/_user.html.slim
li.list-group-item
  p= response.email

app/views/search/index.html.slim
- if @results.any?
    h2 Results
    .list-group
      - @results.each do |response|
        = render "#{response.class.name.downcase}", response: response
- else
    h4.text-center= "Not found"