config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end
  resources :attachments, only: [:destroy]

  resources :search, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
  
  mount ActionCable.server => '/cable'
  
end

app/models/answer.rb
class Answer < ApplicationRecord

  include Votable
  include Commentable
  
  belongs_to :user
  belongs_to :question, touch: true
  has_many :attachments, as: :attachmentable, dependent: :destroy


  validates :body, presence: true
  validates :body, length: { minimum: 5, maximum: 255 }

  accepts_nested_attributes_for :attachments, reject_if: :all_blank

  default_scope { order("best DESC, created_at") }

  after_create :notify_question_subscribers

  def set_best
    Answer.transaction do
      question.answers.update_all(best:false)
      raise ActiveRecord::Rollback unless question.answers.where(best: true).first.nil?
      update!(best:true)
    end  
  end

  private

  def notify_question_subscribers
    NotifySubscribersJob.perform_later(self, question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  include Voted

  before_action :authenticate_user!
  before_action :set_answer, only: [:update, :destroy, :best]
  before_action :set_question, only: [:create, :best]
  after_action :publish_answer, only: [:create]

  respond_to :js
  respond_to :json, only: :create

  authorize_resource
  
  def create
    respond_with(@answer = @question.answers.create(answers_params.merge(user: current_user)))
  end

  def update
    respond_with (@answer.update(answers_params)) if current_user.check_author(@answer)
  end

  def destroy
    @answer.destroy if current_user.check_author(@answer)
    respond_with @answer
  end

  def best
    respond_with @answer.set_best
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
    gon.question_id = @question.id
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answers_params
    params.required(:answer).permit(:body, :question_id, attachments_attributes: [:file, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast(
      "answers_#{@answer.question_id}",
      @answer
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  authorize_resource

  before_action :get_answer, only: [:show]
  before_action :get_question, only: [:index, :create]

  def index
    respond_with @question.answers
  end

  def show
    respond_with @answer, serializer: SingleAnswerSerializer
  end

  def create
    respond_with @question.answers.create(answer_params)
  end

  private

  def get_answer
    @answer = Answer.find(params[:id])
  end

  def get_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body).merge(user: @current_resource_owner)
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
hr
div id="answer_#{answer.id} #{'best-answer' if answer.best}"
  a name="answer_#{answer.id}"
  - if answer.persisted?
    - cache answer do
      .answer-text = answer.body
      = render 'votes/vote', resource: answer
      .answer-comments
      - if user_signed_in?
          div id="add-comment-to-answer-#{answer.id}"
            = render partial: 'comments/form', locals: { commentable: answer }
      -if answer.comments.any?
        = render answer.comments
      -else
        p No comments yet
      -if answer.attachments.any?
        p Attachments:
        ul
          - answer.attachments.each do |a|
            div id="attach_#{a.id}"
              li= link_to a.file.identifier, a.file.url
              - if user_signed_in? && current_user.check_author(a.attachmentable)
                li= link_to 'delete', attachment_path(a), method: :delete, remote: true, data: {confirm: "Are you sure?"}
      -else 
        p No attachments yet
      - if !answer.best? && user_signed_in? && current_user.check_author(answer.question)
        = link_to 'Make best', best_answer_path(answer), method: :patch, remote: true, class: "btn btn-default make-best-link"
      -if can?(:edit, answer)
        = link_to 'Edit', '', class: 'edit-answer-link btn btn-default', data: { answer_id: answer.id }
      -if can?(:destroy, answer)
        = link_to 'Delete', [answer], class: 'delete-answer-link btn btn-default ', method: :delete, remote: true, data: {confirm: "Are you sure?"}
        p = form_for [answer], remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
            p= f.label :body, 'Answer'
            p= f.text_area :body
            p= f.submit 'Save', class: 'btn btn-default'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append('<%= j render @answer %>');
  $('textarea#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
$('#answer_<%= @answer.id %>').remove();
<% end %>

app/views/answers/show.html.slim
h1 = @question.title
p = @question.body
p = @answer.body

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('#answer_'+'<%= @answer.id %>').html('<%= j render @answer %>');
    $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    });
<% end %>