config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  concern :votable do
    member do
      patch :vote_up
      patch :vote_down
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true do
      patch :best, on: :member
    end
    resources :subscriptions, only: [:create, :destroy], shallow: true
  end
  resources :attachments, only: [:destroy]

  resources :search, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles do
        get :me, on: :collection
        get :list, on: :collection
      end
      resources :questions, only: [:index, :show, :create] do
        resources :answers, only: [:index, :show, :create], shallow: true
      end
    end
  end
  
  mount ActionCable.server => '/cable'
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question, touch: true

  validates :user_id, :question_id, presence: true
  validates :user_id, uniqueness: { scope: :question_id }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  respond_to :js

  authorize_resource

  def create
    @question = Question.find(params[:question_id])
    @subscription = Subscription.create(question: @question, user: current_user)
    respond_with(@subscription)
  end

  def destroy
    @subscription = Subscription.find(params[:id])
    respond_with(@subscription.destroy)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_subscription.html.slim
- if current_user && current_user.subscriptions.find_by(question_id: @question.id)
  b.subscribed you are subscribed on this question
- if current_user
  .subscription
  - if current_user.subscriptions.find_by(question_id: @question.id)
      = link_to 'cancel subscription',subscription_path(@question.subscriptions.find_by(user_id:current_user.id)), method: :delete, remote: true, id: 'button_unsubscribe', class: 'btn btn-default'
  - else
      = button_to 'subscribe', question_subscriptions_path(@question), remote: true, id: 'button_subscribe', class: 'btn btn-default'

app/views/subscriptions/create.js.erb
<% if @subscription.errors.any? %>
  <% @subscription.errors.full_messages.each do |message| %>
    $('#subscription').before('<%= j message %>')
  <% end %>
<% else %>
  $('#button_subscribe').hide();
  $('div.subscription').prepend('<%= link_to "cancel subscription", subscription_path(@subscription), method: :delete, remote: true, id: "button_unsubscribe"%>');
  $('div.question').prepend('<b class="subscribed"> you are subscribed on this question </b>')
<% end %>

app/views/subscriptions/destroy.js.erb
$('#button_unsubscribe').remove()
$('div.subscription').prepend('<%= button_to "subscribe", question_subscriptions_path(@subscription.question), remote: true, id: "button_subscribe"%>');
$('b.subscribed').remove()